# Generated by Django 5.2.7 on 2025-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('model', models.CharField(choices=[('Model_A', 'AI Model A'), ('Model_B', 'AI Model B'), ('Model_C', 'AI Model C')], max_length=100)),
                ('confidence', models.FloatField()),
                ('xai_image', models.ImageField(upload_to='xai_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
