# Generated by Django 5.2.7 on 2025-12-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('model', models.CharField(choices=[('Model_A', 'AI Model A'), ('Model_B', 'AI Model B'), ('Model_C', 'AI Model C')], max_length=100)),
                ('confidence', models.FloatField()),
                ('xai_image', models.ImageField(upload_to='xai_images/')),
                ('image_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='AI_Engine.imagesample')),
            ],
        ),
    ]
