# Generated by Django 5.2.7 on 2025-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresult',
            name='model',
            field=models.CharField(choices=[('Model_A', 'EfficientNet'), ('Model_C', 'AI Model C')], max_length=100),
        ),
    ]
