# Generated by Django 5.2.7 on 2025-11-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI_Engine', '0001_initial'),
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesample',
            name='checkup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_samples', to='checkup.checkup'),
        ),
        migrations.AddField(
            model_name='imageresult',
            name='image_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='AI_Engine.imagesample'),
        ),
    ]
