# Generated by Django 5.2.7 on 2025-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Engine', '0002_alter_imageresult_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresult',
            name='xai_image',
            field=models.ImageField(blank=True, null=True, upload_to='xai_images/'),
        ),
    ]
