# Generated by Django 5.2.7 on 2025-11-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_type', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCancerCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_size_mm', models.FloatField()),
                ('lesion_location', models.CharField(max_length=100)),
                ('asymmetry', models.BooleanField()),
                ('border_irregularity', models.BooleanField()),
                ('color_variation', models.BooleanField()),
                ('diameter_mm', models.FloatField()),
                ('evolution', models.BooleanField()),
            ],
        ),
    ]
