# Generated by Django 5.2.7 on 2025-11-26 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skincancercheckup',
            name='checkup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_cancer', to='checkup.checkup'),
        ),
    ]
