# Generated by Django 5.2.7 on 2025-12-02 07:03

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_initial'),
    ]

    def copy_checkup_ptr(apps, schema_editor):
        Skin = apps.get_model('checkup', 'SkinCancerCheckup')
        # Copy existing `checkup_id` values into the new `checkup_ptr_id` field
        for obj in Skin.objects.all():
            # historical model still has `checkup_id`; copy if present
            val = getattr(obj, 'checkup_id', None)
            if val is not None:
                setattr(obj, 'checkup_ptr_id', val)
                obj.save(update_fields=['checkup_ptr_id'])

    def noop_reverse(apps, schema_editor):
        # no-op reverse
        return

    operations = [
        # 1) add nullable parent-link field
        migrations.AddField(
            model_name='skincancercheckup',
            name='checkup_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='checkup.checkup'),
        ),
        # 2) populate it from existing checkup FK
        migrations.RunPython(copy_checkup_ptr, reverse_code=noop_reverse),
        # 3) make the new parent-link non-null and primary key
        migrations.AlterField(
            model_name='skincancercheckup',
            name='checkup_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkup.checkup'),
        ),
        # 4) remove the old FK field (now redundant)
        migrations.RemoveField(
            model_name='skincancercheckup',
            name='checkup',
        ),
        # 5) remove the old id field (old PK)
        migrations.RemoveField(
            model_name='skincancercheckup',
            name='id',
        ),
    ]
