# Generated by Django 5.2.7 on 2025-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincancercheckup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincancercheckup',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincancercheckup',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincancercheckup',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
