# Generated by Django 5.2.7 on 2025-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0003_skincancercheckup_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincancercheckup',
            name='checkup_type',
            field=models.CharField(choices=[('SKIN_CANCER', 'Skin Cancer'), ('MRI_ALZHEIMER', 'MRI Alzheimer'), ('DIABETES_RETINOPATHY', 'Diabetes Retinopathy')], default='SKIN_CANCER', max_length=50),
        ),
    ]
