# Generated by Django 5.2.7 on 2025-12-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0004_skincancercheckup_checkup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincancercheckup',
            name='final_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skincancercheckup',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
