# Generated by Django 5.2.7 on 2025-12-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0005_skincancercheckup_final_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincancercheckup',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
