# Generated by Django on 2026-01-08
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkup", "0006_skincancercheckup_image_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="skincancercheckup",
            name="failure_refund",
            field=models.BooleanField(default=False),
        ),
    ]
