# Generated by Django 5.2.7 on 2025-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
