# Generated by Django 5.2.7 on 2025-12-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_staff',
        ),
    ]
