# Generated by Django 5.2.7 on 2025-12-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LOGGED_OUT', 'Logged Out'), ('SUSPENDED', 'Suspended'), ('NOT_VERIFIED', 'Not Verified')], default='NOT_VERIFIED', max_length=20),
        ),
    ]
