# Generated by Django 5.2.7 on 2025-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
