# Generated by Django 5.2.7 on 2026-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_doctorprofile_license_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="email_verification_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("VERIFIED", "Verified")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "Verified"),
                    ("SUSPENDED", "Suspended"),
                    ("NOT_VERIFIED", "Not Verified"),
                ],
                default="NOT_VERIFIED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="license_image",
            field=models.ImageField(default="General", upload_to="licenses/"),
            preserve_default=False,
        ),
    ]
