# Generated by Django 5.2.7 on 2026-01-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_doctorprofile_email_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
    ]
