# Generated by Django 5.2.7 on 2026-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_doctorprofile_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("doctor", "Doctor")], max_length=20
            ),
        ),
    ]
