# Generated by Django 5.2.7 on 2026-01-11 16:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfileToVerify",
            fields=[],
            options={
                "verbose_name": "Accounts Verifying",
                "verbose_name_plural": "Accounts Verifying",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.doctorprofile",),
        ),
        migrations.CreateModel(
            name="DoctorUser",
            fields=[],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
